version: '{build}'
pull_requests:
  do_not_increment_build_number: true
before_build:
- cmd: nuget restore src/Microsoft.Owin.Security.ApiKey.sln
nuget:
  disable_publish_on_pr: true
build:
  verbosity: minimal
notifications:
- provider: GitHubPullRequest
  auth_token:
    secure: PcfzHEIhC3posOGldSckoUnKi0/1XbrhKMGd5LPYmbiUxGm/drdywDVqgFE+M84D
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true